apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: zookeeper-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30849
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
  sessionAffinity: None
  type: NodePort
