apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hub-bridge
  name: hub-bridge
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hub-bridge
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hub-bridge
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-Xms64m"
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        - name: SMARTY_AUTH_ID
          valueFrom:
            secretKeyRef:
              key: smarty.auth.id
              name: shared
        - name: SMARTY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: smarty.auth.token
              name: shared
        - name: BILLING_PUBLIC_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.public.api.key
              name: shared
        - name: cassandra_contactPoints
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_CONTACTPOINTS
              name: arcus-config
        - name: cassandra_history_contactPoints
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_CONTACTPOINTS
              name: arcus-config
        - name: CASSANDRA_KEYSPACE
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_KEYSPACE
              name: arcus-config
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: BOOTSTRAP_SERVERS
              name: arcus-config
              name: arcus-config
        - name: OPS_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: OPS_BOOTSTRAP_SERVERS
              name: arcus-config
        - name: BOUNCE_HELP_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_HELP_URL
              name: arcus-config
        - name: BOUNCE_APPLE_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_APPLE_URL
              name: arcus-config
        - name: BOUNCE_APPLE_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_APP_URL
              name: arcus-config
        - name: BOUNCE_APP_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_APP_URL
              name: arcus-config
        - name: BOUNCE_ANDROID_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_ANDROID_URL
              name: arcus-config
        - name: BOUNCE_WEB_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_WEB_URL
              name: arcus-config
        - name: BOUNCE_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_REDIRECT_URL
              name: arcus-config
        - name: REDIRECT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: REDIRECT_BASE_URL
              name: arcus-config
        - name: IOS_APP_IDS
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_IOS_APP_IDS
              name: arcus-config
        - name: VIDEO_PREVIEW_UPLOAD_URL
          valueFrom:
            configMapKeyRef:
              key: VIDEO_PREVIEW_UPLOAD_URL
              name: arcus-config
        - name: SECURE_STATIC_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: SECURE_STATIC_RESOURCE_BASE_URL
              name: arcus-config
        - name: INVOICE_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: INVOICE_RESOURCE_BASE_URL
              name: arcus-config
        - name: STATIC_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: SECURE_STATIC_RESOURCE_BASE_URL # only secure, no http
              name: arcus-config
        - name: CAMERA_PREVIEW_BASEURL
          valueFrom:
            configMapKeyRef:
              key: CAMERA_PREVIEW_BASEURL
              name: arcus-config
        - name: FIRMWARE_DOWNLOAD_HOST
          valueFrom:
            configMapKeyRef:
              key: HUB_FIRMWARE_DOWNLOAD_HOST # I think this should be the same.
              name: arcus-config
        - name: TLS_SERVER_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: tls.server.truststore.password
              name: shared
        - name: TLS_SERVER_PRIVATEKEY_FILEPATH
          value: /data/tls-secrets/tls.key
        - name: TLS_SERVER_CERT_FILEPATH
          value: /data/tls-secrets/tls.crt
        - name: TLS_SERVER_TRUSTSTORE_FILEPATH
          value: /data/secrets/truststore.jks
        volumeMounts:
        - name: data-secrets
          mountPath: "/data/tls-secrets"
          readOnly: true
        - name: trust-store
          mountPath: "/data/secrets"
          readOnly: true
        image: gcr.io/arcus-238802/eyeris/hub-bridge:2018.10.2
        imagePullPolicy: Always
        name: hub-bridge
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          tcpSocket:
            port: 9082
          initialDelaySeconds: 15
          periodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-secrets
        secret:
          secretName: hub-keystore
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      - name: trust-store
        secret:
          secretName: truststore
          items:
          - key: truststore.jks
            path: truststore.jks

