apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ipcd-bridge
  name: ipcd-bridge
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ipcd-bridge
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ipcd-bridge
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: cluster-config
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx96m"
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        - name: SMARTY_AUTH_ID
          valueFrom:
            secretKeyRef:
              key: smarty.auth.id
              name: shared
        - name: SMARTY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: smarty.auth.token
              name: shared
        - name: BILLING_PUBLIC_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.public.api.key
              name: shared
        - name: TLS_SERVER
          value: "false"
        - name: USE_SSL
          value: "false"
        image: gcr.io/arcus-238802/arcus/ipcd-bridge:2019.10.0
        imagePullPolicy: Always
        name: ipcd-bridge
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.05"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
