apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kairosdb
  name: kairosdb
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kairosdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kairosdb
    spec:
      containers:
      - image: gcr.io/arcus-238802/eyeris/kairosdb:latest
        imagePullPolicy: Always
        name: kairosdb
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.1"
        ports:
        - containerPort: 8080
          name: tcp-8080
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
