apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platform-services
  name: platform-services
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-services
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: platform-services
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: cluster-config
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx128m -Dlogback.configurationFile=/config/logback.xml"
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        - name: SMARTYSTREETS_AUTHID
          valueFrom:
            secretKeyRef:
              key: smartystreets.authid
              name: shared
        - name: SMARTYSTREETS_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              key: smartystreets.authtoken
              name: shared
        - name: REDIRECT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: REDIRECT_BASE_URL
              name: arcus-config
        - name: INVOICE_URL
          valueFrom:
            configMapKeyRef:
              key: INVOICE_URL
              name: arcus-config
        - name: PLATFORM_ADDRESS_VALIDATOR
          valueFrom:
            configMapKeyRef:
              key: ADDRESS_VALIDATOR
              name: arcus-config
        - name: DEFAULT_SERVICE_LEVEL
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_SERVICE_LEVEL
              name: arcus-config
        image: gcr.io/arcus-238802/arcus/platform-services:2019.10.0
        imagePullPolicy: Always
        name: platform-services
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform-services
  name: platform-services
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: platform-services
  sessionAffinity: None
  type: NodePort
