apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rule-service
  name: rule-service
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rule-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rule-service
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: cluster-config
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx128m -Dlogback.configurationFile=/config/logback.xml"
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        image: gcr.io/arcus-238802/arcus/rule-service:2019.10.0
        imagePullPolicy: Always
        name: rule-service
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "10m"
            memory: "128Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
         - mountPath: /config
           name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: extrafiles
          items:
          - key: logback.xml
            path: logback.xml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rule-service
  name: rule-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: rule-service
  sessionAffinity: None
  type: NodePort
