apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subsystem-service
  name: subsystem-service
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: subsystem-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: subsystem-service
    spec:
      containers:
      - env:
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        - name: cassandra_contactPoints
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_CONTACTPOINTS
              name: arcus-config
        - name: cassandra_history_contactPoints
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_CONTACTPOINTS
              name: arcus-config
        - name: CASSANDRA_KEYSPACE
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_KEYSPACE
              name: arcus-config
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: BOOTSTRAP_SERVERS
              name: arcus-config
              name: arcus-config
        - name: OPS_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: OPS_BOOTSTRAP_SERVERS
              name: arcus-config
        - name: REDIRECT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: REDIRECT_BASE_URL
              name: arcus-config
        - name: NEST_LOGIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: NEST_LOGIN_BASE_URL
              name: arcus-config
        - name: NEST_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: NEST_CLIENT_ID
              name: arcus-config
        - name: DEVICE_OTA_FIRMWARE_DOWNLOAD_HOST
          valueFrom:
            configMapKeyRef:
              key: DEVICE-OTA-FIRMWARE_DOWNLOAD_HOST
              name: arcus-config
        image: gcr.io/arcus-238802/eyeris/subsystem-service:2019.10.0
        imagePullPolicy: Always
        name: subsystem-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: subsystem-service
  name: subsystem-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: subsystem-service
  sessionAffinity: None
  type: NodePort
