apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
    spec:
      containers:
      - image: gcr.io/arcus-238802/eyeris/zookeeper:latest
        imagePullPolicy: Always
        name: zookeeper
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.1"
        env:
        - name: CLIENT_PORT_ADDRESS
          value: 127.0.0.1
        ports:
        - containerPort: 2181
          name: tcp-2181
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
