apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: modelmanager-history
    app.kubernetes.io/version: 2018.10.2
  name: modelmanager-history
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: modelmanager-history
    spec:
      containers:
      - env:
        - name: MODELMANAGER_HOME
          value: /modelmanager-2018.10.2/history-resources/
        - name: MODELMANAGER_SCHEMA
          value: history
        - name: MODELMANAGER_AUTO
          value: "true"
        - name: cassandra_history_contactPoints
          value: cassandra-service.default.svc.cluster.local
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: BOOTSTRAP_SERVERS
              name: arcus-config
              name: arcus-config
        - name: OPS_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: OPS_BOOTSTRAP_SERVERS
              name: arcus-config
        image: gcr.io/arcus-238802/eyeris/modelmanager:2018.10.2
        imagePullPolicy: Always
        command: ["/modelmanager-2018.10.2/bin/modelmanager"]
        args: ["-c", "/modelmanager-2018.10.2/conf/arcus-modelmanager.properties"]
        name: modelmanager-history
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
