apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: apple-apns
spec:
  hosts:
  - gateway.push.apple.com
  - feedback.push.apple.com
  - gateway.sandbox.apple.com
  - feedback.sandbox.apple.com
  ports:
  - number: 2195
    name: https-2195
    protocol: TLS
  - number: 2196
    name: https-2196
    protocol: TLS
  resolution: NONE
  location: MESH_EXTERNAL

