apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: sendgrid
spec:
  hosts:
  - api.sendgrid.com
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: NONE
  location: MESH_EXTERNAL
