apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: smartystreets
spec:
  hosts:
  - us-street.api.smartystreets.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
