apiVersion: v1
data:
  ADVERTISED_HSTN: kafka-service.default.svc.cluster.local
  BILLING_TOKEN_URL: https://api.recurly.com/js/v1/token
  BILLING_URL: https://arcus.wl-net.net
  BOOTSTRAP_SERVERS: kafka-service.default.svc.cluster.local:9092
  BOUNCE_ANDROID_URL: https://arcus.wl-net.net
  BOUNCE_APP_URL: https://arcus.wl-net.net
  BOUNCE_APPLE_URL: https://arcus.wl-net.net
  BOUNCE_HELP_URL: https://arcus.wl-net.net
  BOUNCE_IOS_APP_IDS: "12345"
  BOUNCE_REDIRECT_URL: https://arcus.wl-net.net
  BOUNCE_WEB_URL: https://arcus.wl-net.net
  CAMERA_PREVIEW_BASEURL: https://camera.preview.arcus.wl-net.net
  CASSANDRA_CONTACTPOINTS: cassandra-service.default.svc.cluster.local
  CASSANDRA_HOST: cassandra-service.default.svc.cluster.local
  CASSANDRA_KEYSPACE: production
  CASSANDRA_SINGLE_NODE: "true"
  INVOICE_RESOURCE_BASE_URL: https://invoice.arcus.wl-net.net
  KAFKA_HSIZE: "512"
  KAFKAOPS_REPLICATION: "1"
  OPS_BOOTSTRAP_SERVERS: kafka-service.default.svc.cluster.local
  REDIRECT_BASE_URL: https://arcus.wl-net.net
  SECURE_STATIC_RESOURCE_BASE_URL: https://static.arcus.wl-net.net
  VIDEO_PREVIEW_UPLOAD_URL: https://video.arcus.wl-net.net
  ZOOKEEPER: zookeeper-service.default.svc.cluster.local:2181
  ZOOKEEPEROPS: zookeeper-service.default.svc.cluster.local:2181
  NEST_LOGIN_BASE_URL: http://example.com
  NEST_CLIENT_ID: "12345"
  DEVICE-OTA-FIRMWARE_DOWNLOAD_HOST: https://tools.arcus.wl-net.net
  HUB_FIRMWARE_DOWNLOAD_HOST: https://tools.arcus.wl-net.net
  INVOICE_URL: https://arcus.wl-net.net
  ARCUS_WS_URI: wss://arcus.wl-net.net
  ARCUS_HTTP_URI: https://arcus.wl-net.net
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: arcus
  name: arcus-config
  namespace: default
  selfLink: /api/v1/namespaces/default/configmaps/arcus-config
  uid: 1040bd41-6881-11e9-90e9-42010a800116
