apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cassandra
  namesace: default
spec:
  host: cassandra-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
