apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: default
spec:
  serviceName: cassandra
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cassandra
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cassandra
    spec:
      containers:
      - env:
        - name: CASSANDRA_HOST1
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_HOST
              name: arcus-config
        - name: CASSANDRA_SINGLE_NODE
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_SINGLE_NODE
              name: arcus-config
        image: gcr.io/arcus-238802/eyeris/cassandra:latest
        imagePullPolicy: IfNotPresent
        name: cassandra-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: "/data"
          name: cassandra-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

  volumeClaimTemplates:
  - metadata:
      name: cassandra-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
