apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certprovider/letsencrypt-production.yml
- certprovider/letsencrypt-staging.yml
- cloud-generic.yaml
- deployments/alarm-service.yml
- deployments/client-bridge.yml
- deployments/driver-services.yml
- deployments/history-service.yml
- deployments/hub-bridge.yml
- deployments/ivr-callback-server.yml
- deployments/notification-services.yml
- deployments/platform-services.yml
- deployments/rule-service.yml
- deployments/scheduler-service.yml
- deployments/static-server.yml
- deployments/subsystem-service.yml
- deployments/ui-server.yml
- deployments/zookeeper.yml
- destinationrules/cassandra.yml
- destinationrules/zookeeper.yml
- istio/sendgrid.yml
- istio/smartystreets.yml
- istio/twilio.yml
- jobs/modelmanager-history.yml
- jobs/modelmanager-platform.yml
- jobs/modelmanager-video.yml
- service/cassandra.yml
- service/client-bridge.yml
- service/hub-bridge.yml
- service/ivr-callback-server.yml
- service/kafka.yml
- service/static-service.yml
- service/ui-service-ingress.yml
- service/ui-service.yml
- service/zookeeper.yml
- shared-config/config.yml
- stateful/cassandra.yaml
- stateful/kafka.yaml
