# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: modelmanager
  name: modelmanager
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: modelmanager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: modelmanager
    spec:
      containers:
      - env:
        - name: MODELMANAGER_HOME
          value: /modelmanager-2018.10.2/
        - name: MODELMANAGER_AUTO
          value: "true"
        - name: CASSANDRA_PLATFORM_CONTACTPOINTS
          value: cassandra-service.default.svc.cluster.local
        image: gcr.io/arcus-238802/eyeris/modelmanager@sha256:2af8631055c5816996bb9da70fba37845b3bb3292bd69a431c4b5464dbbb5ef7
        imagePullPolicy: IfNotPresent
        name: modelmanager-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-04-27T15:56:03Z"
    lastUpdateTime: "2019-04-27T15:56:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 24
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
