# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: modelmanager-platform
  name: modelmanager-platform
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: modelmanager-platform
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: modelmanager-platform
    spec:
      containers:
      - env:
        - name: MODELMANAGER_HOME
          value: /modelmanager-2018.10.2/history-resources
        - name: MODELMANAGER_AUTO
          value: "true"
        - name: CASSANDRA_PLATFORM_CONTACTPOINTS
          value: cassandra-service.default.svc.cluster.local
        image: gcr.io/arcus-238802/eyeris/modelmanager:2018.10.2
        #        imagePullPolicy: IfNotPresent
        name: modelmanager-platform-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
