apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: arcus-ip-space
      protocol: layer2
      addresses:
      - 172.16.6.1-172.16.6.15  # configure to your needs.
